# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish snapshots to GitHub Packages
on:
  push:
    branches: 
      - development
      
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.MYGPGKEY_SEC }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.MYGPGKEY_SEC }}
          passphrase: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Delete old Package
        uses: actions/delete-package-versions@v1
        continue-on-error: true
        with:
          package-name: 'com.sap.dsc.aas.lib.aas-transformation-library'

      - name: Publish package
        run: ./gradlew -i publish -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
